GET http://localhost:8080/todos 
# get all

###
GET http://localhost:8080/todos/617fb4a00fd23ea0c5cadde7
#get one

###
POST http://localhost:8080/todos
Content-Type: application/json

{
  "title": "buy milk",
  "completed": false
}

###

DELETE http://localhost:8080/todos/61802d21a0bbe6e332c17268

###
PATCH http://localhost:8080/todos/617fe8486c07811a5aa06020
Content-Type: application/json

{
  "completed": true
}

###
